### ISSUE TITLE
Verifiy that the auditor and musican communicate

### ISSUE THREAD

**Issue by Balkghar** [a-mango/dai-lab-udp#9]
You should be able to start an **Auditor** container with the following command:

```
$ docker run -d -p 2205:2205 dai/auditor
```

You should be able to connect to your **Auditor** container over TCP and see that there is no active musician.

```
$ telnet localhost 2205
[]
```

You should then be able to start a first **Musician** container with the following command:

```
$ docker run -d dai/musician piano
```

After this, you should be able to verify two points. Firstly, if you connect to the TCP interface of your **Auditor** container, you should see that there is now one active musician (you should receive a JSON array with a single element). Secondly, you should be able to use `tcpdump` to monitor the UDP datagrams generated by the **Musician** container.

You should then be able to kill the **Musician** container, wait 5 seconds and connect to the TCP interface of the **Auditor** container. You should see that there is now no active musician (empty array).

You should then be able to start several **Musician** containers with the following commands:

```
$ docker run -d dai/musician piano
$ docker run -d dai/musician flute
$ docker run -d dai/musician flute
$ docker run -d dai/musician drum
```
When you connect to the TCP interface of the **Auditor**, you should receive an array of musicians that corresponds to your commands. You should also use `tcpdump` to monitor the UDP trafic in your system.

**Comment by a-mango** [comment]
Manual tests are working as expected.

Automated tests are throwing an assertion error. Here is the whole log:

```txt
*** Starting validation...

origin	git@github.com:a-mango/dai-lab-udp.git (fetch)
origin	git@github.com:a-mango/dai-lab-udp.git (push)
Starting container dai/musician: "37b67aeb822e916b54ec44b38bb58a515152c812afff642e6330db8c87fc41df"
Starting container dai/musician: "84b5baae16f5d7c8768bf9800a9d5df7bbfe31ce6df031708d896f5bca9e246a"
Starting container dai/musician: "d13b1ecf2e86750f981ac711f252304e53c2b5eb86db615f9bcaa21ef1d62366"
Starting container dai/musician: "b8dad4a3dfd1561c0d35aadd7889f965ca1301362ff3a56d25df54e820854674"
Starting container dai/musician: "d32f2ed82d337e4d97dc4f32e17583f644909b8a619734493048d8fae11e5313"
Starting container dai/musician: "8c6347bfe60b9862f866565fd1a126f005b9200ea29fa658fccaac53418ca1a1"
Starting container dai/musician: "e59056ca90278d5d66c38c7a9c0ced3eda4b5cc8fbb0018ff3bd7f2d9f9af458"
Starting container dai/musician: "aef76f9cc3d21663354cc495cb6d89ab89cc7df01e9d13e010cae87f0ac7709c"
Starting container dai/auditor: "4a0c3dd7f2edbc52d01eb140cad8f9ea3a09c634d15db0640d767ab0b11f6b60"
Starting container dai/musician: "4527d44c51a32359ab92cba3d10587976a618f4f250e0407675967fc571e9626"
Starting container dai/musician: "59e49a4bbf08fddb907430326e929ac7b07305452987bbf5bd030d78e0b09a52"
11 containers have been started.
e59056ca90278d5d66c38c7a9c0ced3eda4b5cc8fbb0018ff3bd7f2d9f9af458 : java -jar,/app/app.jar,trumpet
aef76f9cc3d21663354cc495cb6d89ab89cc7df01e9d13e010cae87f0ac7709c : java -jar,/app/app.jar,flute
59e49a4bbf08fddb907430326e929ac7b07305452987bbf5bd030d78e0b09a52 : java -jar,/app/app.jar,trumpet
8c6347bfe60b9862f866565fd1a126f005b9200ea29fa658fccaac53418ca1a1 : java -jar,/app/app.jar,drum
d32f2ed82d337e4d97dc4f32e17583f644909b8a619734493048d8fae11e5313 : java -jar,/app/app.jar,drum
84b5baae16f5d7c8768bf9800a9d5df7bbfe31ce6df031708d896f5bca9e246a : java -jar,/app/app.jar,flute
4527d44c51a32359ab92cba3d10587976a618f4f250e0407675967fc571e9626 : java -jar,/app/app.jar,flute
d13b1ecf2e86750f981ac711f252304e53c2b5eb86db615f9bcaa21ef1d62366 : java -jar,/app/app.jar,drum
37b67aeb822e916b54ec44b38bb58a515152c812afff642e6330db8c87fc41df : java -jar,/app/app.jar,drum
b8dad4a3dfd1561c0d35aadd7889f965ca1301362ff3a56d25df54e820854674 : java -jar,/app/app.jar,trumpet
4a0c3dd7f2edbc52d01eb140cad8f9ea3a09c634d15db0640d767ab0b11f6b60 : java -jar,/app/app.jar
Auditor validation: success: ["drum","drum","drum","drum","flute","flute","flute","trumpet","trumpet","trumpet"]
There are 10 musicians, let's kill one
killed 84b5baae16f5d7c8768bf9800a9d5df7bbfe31ce6df031708d896f5bca9e246a

/opt/app/node_modules/chai/lib/chai/assertion.js:107
      throw new AssertionError(msg, {
      ^
AssertionError: expected [ Array(9) ] to deeply equal [ Array(10) ]
    at /opt/app/app.js:106:39
    at /opt/app/node_modules/async/dist/async.js:4827:13
    at /opt/app/node_modules/async/dist/async.js:367:20
    at replenish (/opt/app/node_modules/async/dist/async.js:825:28)
    at /opt/app/node_modules/async/dist/async.js:844:29
    at /opt/app/node_modules/async/dist/async.js:807:20
    at /opt/app/node_modules/async/dist/async.js:4824:17
    at /opt/app/node_modules/async/dist/async.js:307:31
    at Socket.<anonymous> (/opt/app/app.js:60:4)
    at Socket.emit (node:events:531:35) {
  showDiff: true,
  actual: [
    'drum',    'drum',
    'drum',    'drum',
    'flute',   'flute',
    'trumpet', 'trumpet',
    'trumpet'
  ],
  expected: [
    'drum',    'drum',
    'drum',    'drum',
    'flute',   'flute',
    'flute',   'trumpet',
    'trumpet', 'trumpet'
  ]
}

Node.js v21.6.0
```

Does it mean that the musicians are not correctly removed from the auditor's musicians collection after the timeout ? @Balkghar

**Comment by a-mango** [comment]
Closed as manually verified by @Balkghar and @a-mango.
